# malice/avg plugin configuration.

name = 'virustotal'
description = 'Malice VirusTotal Plugin'
category = 'virustotal'
version = '0.1.0'

accepts = [ '*' ]

[system]
cpu = 0.5
ram = 256 # MB

[settings]
